FORMAT: 1A

# pyqdb
Pyqdb-API is a service to access quotes saved in a rash-qdb database in the form of a JSON API.

# Group Quotes
Quotes related resources of the **pyqdb API**

## Quotes Collection [/quotes]
### List all quotes [GET]
+ Response 200 (application/json)

        [{
            "rating": -8,
            "quote": "\"Niemand hat die Absicht, Minecraft zu spielen\" - Notch",
            "authors": ["Notch"],
            "id": 1,
            "timestamp": 1389883016
        },
        {
            "rating": 5,
            "quote": "\"This is another sample quote. Not unlike the one by Notch.\" - Jeb",
            "authors": ["Notch", "Jeb"],
            "id": 2,
            "timestamp": 1389884567
        }
        ]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
